import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import TopNav from "@/components/Top-Nav";
import SideNav from "@/components/Side-Nav";
import {
  House,
  InfoIcon,
  MessageCircleWarning,
  Clock,
  Archive,
  Book,
  Pen,
  List,
  Map,
  Newspaper,
} from "lucide-react";
import MaxWidthWrapper from "@/components/Max-Width-Wrapper";
import { ThemeProvider } from "@/components/theme-provider";

const interSans = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: "normal",
  variable: "--font-inter",
  subsets: ["latin"],
});

const topNavPages = [
  {
    title: "Home",
    path: "/",
    icon: <House size={24} />,
  },
  {
    title: "About",
    path: "/about",
    icon: <InfoIcon size={24} />,
  },
  {
    title: "Map",
    path: "/map",
    icon: <Map size={24} />,
  },
  {
    title: "FAQ",
    path: "/faq",
    icon: <List size={24} />,
  },
];

const sideNavPages = [
  {
    title: "Water Advisories",
    pages: [
      {
        title: "Critical Water Advisories",

        path: "/water-advisories",
        icon: <MessageCircleWarning size={24} />,
      },
      {
        title: "Latest Water Alerts",
        path: "/water-advisories/latest",
        icon: <Clock size={24} />,
      },
      {
        title: "Water Alert Archive",
        path: "/water-advisories/archive",
        icon: <Archive size={24} />,
      },
    ],
  },
  {
    title: "Library",
    pages: [
      {
        title: "Journals & Reports",
        path: "/library/journals-reports",
        icon: <Pen size={24} />,
      },
      {
        title: "Articles",
        path: "/library/articles",
        icon: <Newspaper size={24} />,
      },
      {
        title: "Water Quality Reports",
        path: "/library/water-quality-reports",
        icon: <Book size={24} />,
      },
    ],
  },
];

export const metadata: Metadata = {
  title: "Water Quality Reporter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${interSans.variable} antialiased flex flex-col min-h-screen bg-background text-foreground`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopNav pages={topNavPages} />

          <div className="flex flex-row h-full w-full justify-center align-center items-center py-4  md:py-8 lg:py-14 px-12 md:px-4 min-h-[100vh]">
            <MaxWidthWrapper>
              <div className="grid grid-cols-1 md:grid-cols-4 h-full min-h-[100vh]  w-full ">
                {/* SideNav - Hidden on smaller screens */}
                <aside className="hidden md:flex col-span-1 max-w-[299px] md:h-full">
                  <SideNav categories={sideNavPages} />
                </aside>

                {/* Main content */}
                <main className="col-span-3">{children}</main>
              </div>
            </MaxWidthWrapper>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
